version: '3'
services:
  dind:
    image: docker:dind
    hostname: dind
    networks: 
      - docker-dind
    volumes:
      - docker-ca:/certs/ca
      - docker-client:/certs/client
    environment:
      DOCKER_TLS_CERTDIR: /certs
    privileged: true
  migrator:
    build: .
    ports:
      - 5001:5001
    networks: 
      - docker-dind
    volumes:
      - docker-client:/root/.docker:ro
    environment:
      DOCKER_HOST: tcp://dind:2376
      DOCKER_TLS_VERIFY: 1
volumes:
  docker-ca:
  docker-client:
networks:
    docker-dind:
        driver: bridge
        attachable: true
